---
title: Statistical Consulting
summary: []
date: "2019-11-3"

reading_time: false  # Show estimated reading time?
share: false  # Show social sharing links?
profile: false  # Show author profile?
comments: false  # Show comments?

# Optional header image (relative to `static/img/` folder).
header:
  caption: ""
  image: ""
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Consulting enquiries should be sent to [consulting@dmswan.com](mailto:consulting@dmswan.com).

## General Experience. 

For three years I worked at the University of Texas for the College of Education’s Research Support unit as a methodological consultant on research design and statistical analysis. I worked primarily with graduate students and occasionally assisted with faculty analyses. I have experience with offering quantitative methodological assistance at all stages of the research process. I am an advanced user in R and comfortable with MPLUS. I have also assisted researchers in performing analyses in SPSS and STATA (including complex models like multi-level models and structural equation modeling).

As a graduate student I have taken courses involving: multi-level models, structural equation modeling (various kinds of factor analysis and other latent models), item response theory, meta-analysis, causal inference (regression discontinuity designs, propensity score analyses, etc.), and generalized linear models in addition to the typical t-tests, chi squares, and regression analyses.

My personal methodological research involves single-case designs (a particular form of research design common in special education), generalized linear models, and is meta-analysis adjacent.

## Services offered:

* **Formulating research questions.** Sometimes researchers have identified an area of research they are interested in but need assistance formulating their research questions. This stage is important, because research questions can dictate both the kind of data that need to be gathered and the type of analysis that must be conducted to properly answer that question. Occasionally, inexperienced researchers have one kind of question or research project in mind, and accidentally formulate research questions that imply something quite different. Often minor revisions to research questions can significantly change the implied design and analysis to more closely match the expectations of the researcher.

* **Choosing a statistical model or measurement tool.** In some cases, researchers have very clear ideas about the questions that they want to ask, but are not entirely certain about an appropriate statistical model. In other cases, researchers are sometimes unaware of the consequences of their sampling methods. For instance, in education data, student outcomes are often clustered in classrooms, schools, and districts. If a researcher fails to account for this in their statistical analysis, this can result in significant violations of analytic assumptions and cause biases in their results. Finally, researchers may have outcomes or covariates they would like to measure but are not sure what the appropriate measurement method is. In these cases, I can help researchers choose appropriate methods for their research questions and samples, as well as provide guidance about the selection and use of appropriate measurement tools.

* **Conducting a power analysis.** Performing a power analysis for a full study is important to ensure that researchers are likely to find a statistically significant result, assuming that a substantively meaningful effect is present. In addition, grant proposals often require that researchers perform a power analysis for their intended analytic method. However, power analysis can be tricky.  There are tools like G*Power, PowerUp!, and Optimal Design for a variety of analyses, however they can be opaque. In the case of models with latent outcomes, such as structural equation modeling, the use of Monte Carlo simulations may be required to assess the necessary sample size for a desired power. In addition, finding all statistical values that need to be specified in a power analysis can be difficult, as some of them are often not typically part of published research. I can help guide researchers through the power analysis process with existing software tools or assist in the design and execution of a Monte Carlo simulation power analysis, as well as help researchers figure out appropriate values to be used in the analyses.

*	**Assist with statistical analysis.** For more advanced analyses, researchers are sometimes not comfortable performing them alone. I am happy to help researchers with every step in the analysis process, from cleaning their data, writing code/pointing and clicking on the right spots in software, troubleshooting difficulties in analysis the researchers began independently, all the way up to assisting in the interpretation of the results of an analysis.

Consulting enquiries should be sent to [consulting@dmswan.com](mailto:consulting@dmswan.com).